on: [push, pull_request]
name: CI

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        os: [ubuntu-latest, macos-latest]
        experimental: [false]
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo 'installing Ubuntu dependencies'
          apt update
      - name: Install MacOS dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          echo 'installing MacOS dependencies'
      - name: Install MacOS dependencies
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo 'installing Windows dependencies'
      - name: Build
        run: |
          mkdir -p build
          g++ src/main.cpp -o build/main

# ####################################################
# # BEGIN V0
# ####################################################
# jobs:
#   # ---------------------------------------------
#   # Ubuntu Build/Test
#   # ---------------------------------------------
#   ubuntu-build:
#     runs-on: ubuntu-latest
#     name: Ubuntu $BUILD_TYPE build
#     strategy:
#       matrix:
#         compiler: [g++]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Packages
#         run: |
#           sudo apt-get update
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main
#       - name: Test
#         run: ./build/main
#   # ---------------------------------------------
#   # MacOS Build/Test
#   # ---------------------------------------------
#   macos-build:
#     runs-on: macos-latest
#     name: MacOS $BUILD_TYPE build
#     strategy:
#       matrix:
#         compiler: [g++]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main
#       - name: Test
#         run: ./build/main
#   # ---------------------------------------------
#   # Windows Build/Test
#   # ---------------------------------------------
#   windows-build:
#     runs-on: windows-latest
#     name: Windows $BUILD_TYPE build
#     strategy:
#       matrix:
#         compiler: [g++]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main
#       - name: Test
#         run: ./build/main
# #####################################################
# # END V0
# #####################################################


#         os: [ubuntu-latest, macos-latest]
#         experimental: [false]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main


# jobs:
#   build:
#     strategy:
#       matrix:
#         compiler: [g++]

#     runs-on: ubuntu-latest
#     name: Ubuntu $BUILD_TYPE build

#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Packages
#         run: |
#           sudo apt-get update
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main
