on: [push, pull_request]
name: CI

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        os: [ubuntu-latest, macos-latest]
        experimental: [false]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build
          g++ src/main.cpp -o build/main


# jobs:
#   build:
#     strategy:
#       matrix:
#         compiler: [g++]

#     runs-on: ubuntu-latest
#     name: Ubuntu $BUILD_TYPE build

#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Packages
#         run: |
#           sudo apt-get update
#       - name: Build
#         run: |
#           mkdir -p build
#           g++ src/main.cpp -o build/main
