on: [push, pull_request]
name: CI

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++]

    runs-on: ubuntu-latest #TODO: macos-latest
    name: Debug build 

    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get update
      - name: Build
        run: |
          mkdir -p build
          g++ src/main.cpp -o build/main
